### ISSUE TITLE
Make 'feature proposal' cards clickable

### ISSUE THREAD

**Issue by MBJean** [MBJean/Janiculum#23]
# Overview
RE: a suggestion from Hank, the cards on the front page that described feature proposals look like they're clickable but aren't. Make them clickable and have them toggle open the toolkit. See image for reference:

<img width="962" alt="Screen Shot 2020-03-17 at 3 17 57 PM" src="https://user-images.githubusercontent.com/20114078/76893369-9c80ec80-6862-11ea-845f-b12fa5f38e6a.png">

**Comment by MBJean** [comment]
Hank also suggested we add some kind of border or background color to the sidebar.

**Comment by henrysblume** [comment]
Foo

**Comment by MBJean** [comment]
Resolved by #25
